-- ── clients.plan_type CHECK — NO-OP: FOUND ALREADY APPLIED. ──
--
-- Written 2026-08-21 as a described-and-stopped migration; the founder's pre-run verification
-- found the constraint ALREADY EXISTS, applied by the single_149 migration
-- (20260807000000_plan_type_single_149.sql), covering exactly the ruled four-value set:
--   CHECK (plan_type = ANY (ARRAY['single_99','single_149','growth_279','scale_499']))
-- Live values at verification: single_99 (2), scale_499 (2), growth_279 (1), zero nulls, zero
-- strays. The admin-typo-creates-a-broken-account concern was already structurally closed.
--
-- This file stays as the verification RECORD and executes nothing. Lesson recorded with it:
-- model against the LIVE schema, not the migrations folder.
--
-- READ-BACK (held 2026-08-21):
--   select pg_get_constraintdef(oid) from pg_constraint
--     where conrelid='public.clients'::regclass and conname='clients_plan_type_check';
